config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  resources :posts do
    resources :comments
  end
  resources :categories
  resources :users
  resources :tags
  resources :sessions, only: [:new, :create, :destroy]
  resources :votes do
    member do
      post 'up'
      delete 'down'
    end
  end

  get '/login' => redirect('/sessions/new')
  get '/signup' => redirect('/users/new')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
  validates :title, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  default_scope { order(votes_count: :desc) }

  belongs_to :user
  belongs_to :category

  has_many :votes
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings

  before_validation :smart_add_url_protocol
  validates :url, uniqueness: true
  validates :url, format: { with: /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?\z/ix }
  validates :user, :title, :url, presence: true


  def tag_names
    tags.collect(&:name).join(", ")
  end

  protected

  # Found regular expressions and the method below on Stack Overflow because writing them is awful. But I know what they're doing, so there's that..

  def smart_add_url_protocol
    unless self.url[/\Ahttp:\/\//] || self.url[/\Ahttps:\/\//]
      self.url = "https://#{self.url}"
    end
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :posts, through: :taggings

  def to_param
    name
  end

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :votes
  has_many :comments
  has_secure_password
  validates :username, :email_address, presence: true,
                                       uniqueness: true

  def to_param
    username
  end

end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :post, counter_cache: :votes_count
  belongs_to :user
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to root_path
    else
      render :new
    end
  end

private

def category_params
  params.require(:category).permit(:title)  
end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :locate_post, only: [:index, :show, :new, :create]
  before_action :require_login, only: [:create, :new]

  def index
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = params[:post_id]
    if @comment.save
      flash[:success] = "Thanks!"
      redirect_to post_comments_path(@comment.post_id)
    else
      render :new
    end
  end

  def show
    @comments = []
    @comments << Comment.find_by(post_id: @post.id)
  end

  private

  def locate_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:body, :user, :post)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :locate_post, only: :visit
  before_action :require_login, only: [:create, :new]


  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      tag_names = params[:post][:tag_names].split(",")
      tag_names = tag_names.collect(&:strip)
      tag_names.each do |name|
        @post.tags << Tag.find_or_initialize_by(name: name)
      end
      flash[:success] = "Thanks!"
      redirect_to :root
    else
      render :new
    end
  end

  def visit
    if current_user
      @post.votes.new(post_id: @post.id, user_id: current_user.id)
      @post.save
    end
    redirect_to @post.url
  end

  private

  def locate_post
    @post = Post.find(params[:id])
  end

  def locate_vote
    @post = Post.find(params[:id])
    @vote = Vote.find_by post_id: @post.id
  end

  def post_params
    params.require(:post).permit(:title, :url, :user_id, :category_id, :tag)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :forbid_login, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(
                  username: params[:session][:username]
                )
    if user
      if user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        redirect_to :root
        flash[:success] = "Welcome #{user.username}"
      else
        flash.now[:warning] = "Your password is incorrect."
        render :new
      end
    else
      flash.now[:warning] = "No account found with that name. Would you like to <a href='/signup/'>create an account</a>?".html_safe
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You've been loggged out."
    redirect_to :root
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag = Tag.find_by(name: params[:id])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to :new_post
    else
      flash[:warning] = "Correct highlighted fields."
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email_address, :password)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

before_action :require_login, only: [:up, :down]
before_action :locate_post, only: :up
before_action :locate_vote, only: :down

  def new
    @vote = Vote.new
  end

  def up
    @post.votes.new(post_id: @post.id, user_id: current_user.id)
    if @post.save
      redirect_back(fallback_location: :root)
    end
  end

  def down
    @vote.destroy
    redirect_back(fallback_location: :root)
  end

private

  def locate_post
    @post = Post.find(params[:id])
  end

  def locate_vote
    @post = Post.find(params[:id])
    @vote = Vote.find_by post_id: @post.id, user_id: current_user.id
  end

  def vote_params
    params.require(:vote).permit(:user, :post)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/_comment.html.erb
    <tr>
      <td class="vert-align">
        <%= comment.user.username %>
      </td>
      <td class="vert-align">
        <%= comment.body %>
      </td>
    </tr>

app/views/comments/index.html.erb
<table class="table table-striped">
  <tbody>
    <tr>
      <td class="vert-align">
        <% if current_user || !current_page?(post_comment_path(@post)) %>
          <%= link_to up_vote_path(@post.id), class: "btn btn-xs btn-block", method: :post do %>
            <i class="glyphicon glyphicon-chevron-up"></i>
          <% end %>
        <% end %>
        <p class="text-center nopadding">
          <%= @post.votes_count %>
        <p/>
          <% if current_user %>
            <%= link_to down_vote_path(@post.id, current_user.id), class: "btn btn-xs btn-block", method: :delete do %>
              <i class="glyphicon glyphicon-chevron-down"></i>
            <% end %>
          <% end %>
      </td>
      <td class="vert-align">
        <h3><%= link_to @post.title, @post.url %></h3>
          <h5>Submitted by: <%= link_to @post.user.username, user_path(@post) %></h5>
            <h5>Tagged as:
              <% if @post.tags.any? %>
                <% @post.tags.each do |tag| %>
                  <%= link_to tag.name, tag, class: "btn btn-xs btn-inline btn-info nopadding" %>
                <% end %>
              <% end %>
            </h5>
        <h5 class="text-center">Posted in: <%= @post.category.title %></h3>
      </td>
      <% if @post.comments.any? %>
        <%= render @post.comments %>
      <% end %>
  </tbody>
</table>
<div class="col-xs-5 col-xs-offset-2">
  <%= link_to 'Leave a comment', new_post_comment_path(@post), class: "btn btn-xs btn-inline btn-primary nopadding" %>
</div>

app/views/comments/new.html.erb
<% if @comment.errors.any? %>
  <ul>
    <% @comment.errors.full_messages.each do |err| %>
      <li>
        <%= err %>
      </li>
    <% end %>
  </ul>
<% end %>

<table class="table table-striped">
  <tbody>
    <tr>
      <td class="vert-align">
        <% if current_user || !current_page?(new_post_comment_path(@post)) %>
          <%= link_to up_vote_path(@post.id), class: "btn btn-xs btn-block", method: :post do %>
            <i class="glyphicon glyphicon-chevron-up"></i>
          <% end %>
        <% end %>
        <p class="text-center nopadding">
          <%= @post.votes_count %>
        <p/>
          <% if current_user %>
            <%= link_to down_vote_path(@post.id, current_user.id), class: "btn btn-xs btn-block", method: :delete do %>
              <i class="glyphicon glyphicon-chevron-down"></i>
            <% end %>
          <% end %>
      </td>
      <td class="vert-align">
        <h3><%= link_to @post.title, @post.url %></h3>
          <h5>Submitted by: <%= link_to @post.user.username, user_path(@post) %></h5>
            <h5>Tagged as:
              <% if @post.tags.any? %>
                <% @post.tags.each do |tag| %>
                  <%= link_to tag.name, tag, class: "btn btn-xs btn-inline btn-info nopadding" %>
                <% end %>
              <% end %>
            </h5>
        <h5 class="text-center">Posted in: <%= @post.category.title %></h3>
      </td>
      <% if @post.comments.any? %>
        <%= render @post.comments %>
      <% end %>
  </tbody>
</table>
<div class="col-xs-5 col-xs-offset-2">
  <%= simple_form_for [@post, @comment] do |f| %>
    <div class="input">
      <%= f.input :body, placeholder: "Type your comment here", label: false %>
    </div>
    <div>
      <%= f.button :submit, class: "button btn-xs btn-primary" %>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
    <tr>
      <td class="vert-align">
        <% if current_user || !current_page?(new_post_comment_path(post)) %>
          <%= link_to up_vote_path(post.id), class: "btn btn-xs btn-block", method: :post do %>
            <i class="glyphicon glyphicon-chevron-up"></i>
          <% end %>
        <% end %>
        <p class="text-center nopadding">
        <%= post.votes_count %>
        <p/>
        <% if current_user %>
          <%= link_to down_vote_path(post.id, current_user.id), class: "btn btn-xs btn-block", method: :delete do %>
            <i class="glyphicon glyphicon-chevron-down"></i>
          <% end %>
        <% end %>
      </td>
      <td class="vert-align">
        <h3><%= link_to post.title, post.url %></h3>
        <h5>Submitted by: <%= link_to post.user.username, user_path(post) %></h5>
        <h5>Tagged as:
          <% if post.tags.any? %>
            <% post.tags.each do |tag| %>
              <%= link_to tag.name, tag, class: "btn btn-xs btn-inline btn-info nopadding" %>
            <% end %>
          <% end %>
        </h5>
      <h5 class="text-center">Posted in: <%= post.category.title %></h3>
      </td>
      <td class="vert-align">
        <%= link_to 'Leave a comment', new_post_comment_path(post), class: "btn btn-xs btn-inline btn-primary nopadding" %>
        <h6><%= post.created_at.strftime('%b %e, %Y') %></h6>
      </td>
    </tr>

app/views/posts/index.html.erb
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th>
        Vote!
      </th>
      <th>
        Link
      </th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td class="vert-align">
          <% if current_user %>
            <%= link_to upvote_post_path(post.id), class: "btn btn-xs btn-block", method: :post do %>
              <i class="glyphicon glyphicon-chevron-up"></i>
            <% end %>
          <% end %>
          <p class="text-center nopadding">
          <%= post.votes.count %>
          <p/>
          <% if current_user %>
            <%= link_to downvote_post_path(current_user.id, post.id), class: "btn btn-xs btn-block", method: :delete do %>
              <i class="glyphicon glyphicon-chevron-down"></i>
            <% end %>
          <% end %>
        </td>
        <td class="vert-align">
          <h3><%= link_to post.title, post.url %></h3>
          <h5>Submitted by: <%= link_to post.user.username, user_path(post) %></h5>
          <h6 class="text-right"><%= post.created_at.strftime('%b %e, %Y') %></h6>
          <h5 class='text-center'>Posted in: <%= post.category.title %></h3>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<% if @post.errors.any? %>
  <ul>
    <% @post.errors.full_messages.each do |err| %>
      <li>
        <%= err %>
      </li>
    <% end %>
  </ul>
<% end %>

<div class="col-xs-2">
  <h3><%= button_to "Home", root_path, class: "btn btn-block btn-primary btn-xs", method: :get %></h3>
</div>
<div class="col-xs-8 col-xs-offset-1">
  <%= simple_form_for @post do |f| %>
    <div class="input">
      <%= f.input :title, placeholder: "Title", label: false %>
    </div>
    <div class="input">
      <%= f.input :url, placeholder: "Link address", label: false %>
    </div>
    <div class="input">
      <%= f.input :tag_names, placeholder: "Enter tags (separate with a comma)", label: false %>
    </div>
    <div class="input">
      <%= f.association :category, placeholder: "Choose a category" %>
    </div>
    <div>
      <%= f.button :submit, class: "button btn-xs btn-primary" %>
    </div>
  <% end %>
</div>

app/views/tags/show.html.erb
<h1>Posts tagged with <b><%= @tag.name.titleize %></b></h1>
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th>
        Vote!
      </th>
      <th>
        Link
      </th>
      <th>

      </th>
    </tr>
  </thead>
  <tbody>
    <div class="row">
      <%= render @tag.posts %>
    </div>
  </tbody>
</table>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |err| %>
      <li>
        <%= err %>
      </li>
    <% end %>
  </ul>
<% end %>

<div class="col-xs-2">
  <h3><%= button_to "Home", root_path, class: "btn btn-block btn-primary btn-xs", method: :get %></h3>
</div>
<div class="col-xs-5 col-xs-offset-2">
  <%= simple_form_for @user do |f| %>
    <div class="input">
      <%= f.input :username, placeholder: "Username", label: false %>
    </div>
    <div class="input">
      <%= f.input :email_address, placeholder: "Email", label: false %>
    </div>
    <div class="input">
      <%= f.input :password, placeholder: "Password", label: false %>
    </div>
    <div>
      <%= f.button :submit, class: "button btn-xs btn-primary" %>
    </div>
  <% end %>
</div>